version: '3.4'
services:
    magic_books:
        container_name: magic-books-container
        image: magic-books-image
        build: ./app/
        depends_on: 
          - db
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000

    
    db:
      image: postgres:alpine
      container_name: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: magic_books
      volumes:
        - pgdata/:/var/lib/postgresql/data
      ports:
        - 5432:5432
volumes: 
  pgdata:
    